name: Auto Staging deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      version:
        description: "input your version"
        type: string
        required: false

jobs:
  Build:
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
  Deploy:
    environment: staging
    runs-on: ubuntu-latest
    needs:
      - Build
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: build
      - name: Deploy
        id: deploy
        run: ./deploy/deploy.sh
      - name: onSuccess
        if: ${{ steps.deploy.conclusion == 'success' }}
        run: ./deploy/success.sh
      - name: onFailure
        if: ${{ failure() }}
        run: ./deploy/error.sh
