name: Build

on:
  workflow_call:
  push:
    branches:
      - feat/*
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: ./deploy/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          retention-days: 5
          path: |
            build
