name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build_dev:
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'master'
    with:
      environment: dev
    secrets:                
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build_staging:
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'staging'
    with:
      environment: staging
    secrets:                
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
