name: CI/CD

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

jobs:
  vm2:
    environment: dev
    runs-on: ["self-hosted","vm2"]
    steps:
      - name: uname
        run: uname -a

  whoAmI_dev:
    uses: dongnguyenltqb/baseforci/.github/workflows/whoAmI.yml@master
    if: github.ref_name == 'master'
    with:
      environment: dev
    secrets: inherit
  build_dev:
    needs: [whoAmI_dev]
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'master'
    with:
      environment: dev
    secrets: inherit

  whoAmI_staging:
    uses: dongnguyenltqb/baseforci/.github/workflows/whoAmI.yml@master
    if: github.ref_name == 'staging'
    with:
      environment: staging
    secrets: inherit
  build_staging:
    needs: [whoAmI_staging]
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'staging'
    with:
      environment: staging
    secrets: inherit
