name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  whoAmI_dev:
    uses: dongnguyenltqb/baseforci/.github/workflows/whoAmI.yml@master
    if: github.ref_name == 'master'
    with:
      environment: dev
    secrets: inherit
  build_dev:
    needs: [whoAmI]
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'master'
    with:
      environment: dev
    secrets: inherit

  whoAmI_staging:
    uses: dongnguyenltqb/baseforci/.github/workflows/whoAmI.yml@master
    if: github.ref_name == 'staging'
    with:
      environment: staging
    secrets: inherit
  build_staging:
    uses: dongnguyenltqb/baseforci/.github/workflows/build.yml@master
    if: github.ref_name == 'staging'
    with:
      environment: staging
    secrets: inherit
