name: WhoAmI

on:
  workflow_call:
    inputs:
      environment:
        description: "dev | staging | production"
        type: string
        required: true
    secrets:                
      AWS_DEFAULT_REGION:   
        required: true      
      AWS_ACCESS_KEY_ID:    
        required: true      
      AWS_SECRET_ACCESS_KEY:
        required: true      

jobs:
  whoAmI:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: WhoAmI
        run: |
          #!/bin/bash
          printenv
          aws sts get-caller-identity
